branches:
  only:
    - master

os: Windows Server 2012

clone_folder: c:\pvpgn

install:
  - cmd: cd c:\
  - cmd: appveyor DownloadFile https://github.com/HarpyWar/pvpgn-magic-builder/archive/master.zip
  - cmd: 7z.exe x master.zip >nul
  - cmd: ren pvpgn-magic-builder-master builder
  - cmd: mkdir c:\builder\source\
  - cmd: xcopy /E /R /K /Y /Q "c:\pvpgn" "c:\builder\source\"
  - cmd: cd c:\builder\

before_build:
  - cmd: set APPVEYOR_REPO_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,7%
  - cmd: set COMPLETE_BUILD_VERSION=pvpgn-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_REPO_COMMIT_SHORT%
  - cmd: set PVPGN_PLAIN_ZIP=%COMPLETE_BUILD_VERSION%_plain.zip
  - cmd: set PVPGN_PLAIN_ZIP_DEBUG=%COMPLETE_BUILD_VERSION%_plain_debug.zip
  - cmd: set PVPGN_MYSQL_ZIP=%COMPLETE_BUILD_VERSION%_mysql.zip
  - cmd: set PVPGN_MYSQL_ZIP_DEBUG=%COMPLETE_BUILD_VERSION%_mysql_debug.zip
  - cmd: set PVPGN_PGSQL_ZIP=%COMPLETE_BUILD_VERSION%_pgsql.zip
  - cmd: set PVPGN_PGSQL_ZIP_DEBUG=%COMPLETE_BUILD_VERSION%_pgsql_debug.zip
  - cmd: set PVPGN_SQLITE_ZIP=%COMPLETE_BUILD_VERSION%_sqlite.zip
  - cmd: set PVPGN_SQLITE_ZIP_DEBUG=%COMPLETE_BUILD_VERSION%_sqlite_debug.zip
  - cmd: set PVPGN_ODBC_ZIP=%COMPLETE_BUILD_VERSION%_odbc.zip
  - cmd: set PVPGN_ODBC_ZIP_DEBUG=%COMPLETE_BUILD_VERSION%_odbc_debug.zip

build_script:

  # build gui and console for each storage type
  # build_pvpgn.bat params:
  #  1. automatic build flag
  #  2. visual studio version
  #  3. console or gui
  #  4. storage type
  #  5. with or without lua
  #  6. Release or Debug
  
  # plain
  - cmd: build_pvpgn.bat auto 7 2 1 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 1 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_PLAIN_ZIP% .\release\*
  # plain (debug)
  - cmd: build_pvpgn.bat auto 7 2 1 y Debug
  - cmd: move debug\*.exe
  - cmd: move debug\*.pdb
  - cmd: build_pvpgn.bat auto 7 1 1 y Debug
  - cmd: move /Y *.exe debug
  - cmd: move /Y *.pdb debug
  - cmd: 7z.exe a %PVPGN_PLAIN_ZIP_DEBUG% .\debug\*

  # mysql
  - cmd: build_pvpgn.bat auto 7 2 2 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 2 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_MYSQL_ZIP% .\release\*
  # mysql (debug)
  - cmd: build_pvpgn.bat auto 7 2 2 y Debug
  - cmd: move debug\*.exe
  - cmd: move debug\*.pdb
  - cmd: build_pvpgn.bat auto 7 1 2 y Debug
  - cmd: move /Y *.exe debug
  - cmd: move /Y *.pdb debug
  - cmd: 7z.exe a %PVPGN_MYSQL_ZIP_DEBUG% .\debug\*

  # pgsql
  - cmd: build_pvpgn.bat auto 7 2 3 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 3 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_PGSQL_ZIP% .\release\*
  # pgsql (debug)
  - cmd: build_pvpgn.bat auto 7 2 3 y Debug
  - cmd: move debug\*.exe
  - cmd: move debug\*.pdb
  - cmd: build_pvpgn.bat auto 7 1 3 y Debug
  - cmd: move /Y *.exe debug
  - cmd: move /Y *.pdb debug
  - cmd: 7z.exe a %PVPGN_PGSQL_ZIP_DEBUG% .\debug\*

  # sqlite
  - cmd: build_pvpgn.bat auto 7 2 4 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 4 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_SQLITE_ZIP% .\release\*
  # sqlite (debug)
  - cmd: build_pvpgn.bat auto 7 2 4 y Debug
  - cmd: move debug\*.exe
  - cmd: move debug\*.pdb
  - cmd: build_pvpgn.bat auto 7 1 4 y Debug
  - cmd: move /Y *.exe debug
  - cmd: move /Y *.pdb debug
  - cmd: 7z.exe a %PVPGN_SQLITE_ZIP_DEBUG% .\debug\*

  # odbc
  - cmd: build_pvpgn.bat auto 7 2 5 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 5 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_ODBC_ZIP% .\release\*
  # odbc (debug)
  - cmd: build_pvpgn.bat auto 7 2 5 y Debug
  - cmd: move debug\*.exe
  - cmd: move debug\*.pdb
  - cmd: build_pvpgn.bat auto 7 1 5 y Debug
  - cmd: move /Y *.exe debug
  - cmd: move /Y *.pdb debug
  - cmd: 7z.exe a %PVPGN_ODBC_ZIP_DEBUG% .\debug\*

after_build:
    - PowerShell Push-AppveyorArtifact "%PVPGN_PLAIN_ZIP%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_PLAIN_ZIP_DEBUG%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_MYSQL_ZIP%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_MYSQL_ZIP_DEBUG%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_PGSQL_ZIP%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_PGSQL_ZIP_DEBUG%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_SQLITE_ZIP%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_SQLITE_ZIP_DEBUG%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_ODBC_ZIP%"
    - PowerShell Push-AppveyorArtifact "%PVPGN_ODBC_ZIP_DEBUG%"

# check the latest build executable for exists
test:
  assemblies:
    - '**\src\bnetd\Release\bnetd.exe'
