"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\Launcher.exe"
"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\AMH.dll"
"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\INIFileParser.dll"
"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\OtherInfo.dll"
"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\War3Injector.dll"
"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\ClientUpdater.exe"
:"signtool.exe" sign /f WarcisRoot.pfx /p Venmade1Warcis2Cert3 /t http://timestamp.globalsign.com/scripts/timstamp.dll ".\Release\ClientUpdater\d3d8.fix"
