#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.99.7.2.1.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2019

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  LUA_DIR: C:\Program Files (x86)\Lua\5.1
  CMAKE_GENERATOR: Visual Studio 16 2019
  matrix:
    - DB: plain
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: mysql
      WITH_MYSQL_VAL: true
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: odbc
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: true
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: pgsql
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: true
      WITH_SQLITE3_VA: false
    - DB: sqlite
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: true


matrix:
  fast_finish: true

install:
  - vcpkg install sqlite3 --triplet x64-windows
  - vcpkg install zlib --triplet x64-windows
  - choco install lua

#cache: c:\tools\vcpkg\installed\

#---------------------------------#
#       build configuration       #
#---------------------------------#
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

platform: x64

configuration: RelWithDebInfo

before_build:
  - ps: New-Item -Path "$env:APPVEYOR_BUILD_FOLDER" -Name "build" -ItemType "directory"
  - ps: Set-Location -Path "$env:APPVEYOR_BUILD_FOLDER\build"

build_script:
  - cmd: cmake -A x64 -D CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -D CMAKE_SYSTEM_VERSION=10.0 -D WITH_LUA=true -D WITH_MYSQL=%WITH_MYSQL_VAL% -D WITH_ODBC=%WITH_ODBC_VAL% -D WITH_PGSQL=%WITH_PGSQL_VAL% -D WITH_SQLITE3=%WITH_SQLITE3_VAL% -D WITH_WIN32_GUI=true ..
  - cmd: msbuild ALL_BUILD.vcxproj /property:Configuration=RelWithDebInfo /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\bnetd.exe" -NewName "${Env:Programfiles(x86)}\pvpgn\bnetd-gui.exe"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\bnetd.pdb" -NewName "${Env:Programfiles(x86)}\pvpgn\bnetd-gui.pdb"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\d2cs.exe" -NewName "${Env:Programfiles(x86)}\pvpgn\d2cs-gui.exe"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\d2cs.pdb" -NewName "${Env:Programfiles(x86)}\pvpgn\d2cs-gui.pdb"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\d2dbs.exe" -NewName "${Env:Programfiles(x86)}\pvpgn\d2dbs-gui.exe"
  - ps: Rename-Item -Path "${Env:Programfiles(x86)}\pvpgn\d2dbs.pdb" -NewName "${Env:Programfiles(x86)}\pvpgn\d2dbs-gui.pdb"
  - cmd: cmake -A x64 -D CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -D CMAKE_SYSTEM_VERSION=10.0 -D WITH_LUA=true -D WITH_MYSQL=%WITH_MYSQL_VAL% -D WITH_ODBC=%WITH_ODBC_VAL% -D WITH_PGSQL=%WITH_PGSQL_VAL% -D WITH_SQLITE3=%WITH_SQLITE3_VAL% -D WITH_WIN32_GUI=false ..
  - cmd: msbuild ALL_BUILD.vcxproj /property:Configuration=RelWithDebInfo /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: New-Item -Path "${env:APPVEYOR_BUILD_FOLDER}" -Name "artifacts" -ItemType "directory"
  - ps: Compress-Archive -Path "${Env:Programfiles(x86)}\pvpgn\*" -DestinationPath "${env:APPVEYOR_BUILD_FOLDER}\artifacts\pvpgn-pro-${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_VERSION}-${env:DB}.zip"
  - ps: Get-ChildItem "${env:APPVEYOR_BUILD_FOLDER}\artifacts\*.zip" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
