#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.99.7.2.1.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

environment:
  matrix:
    - DB: plain
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: mysql
      WITH_MYSQL_VAL: true
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: odbc
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: true
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: false
    - DB: pgsql
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: true
      WITH_SQLITE3_VA: false
    - DB: sqlite
      WITH_MYSQL_VAL: false
      WITH_ODBC_VAL: false
      WITH_PGSQL_VAL: false
      WITH_SQLITE3_VA: true


matrix:
  fast_finish: true

install:
  - git -C C:\tools\vcpkg pull
  - vcpkg install libmariadb
  - vcpkg install libpq
  - vcpkg install sqlite3
  - vcpkg install zlib
  - vcpkg install lua

cache: c:\tools\vcpkg\installed\

#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: x86

configuration: RelWithDebInfo

before_build:
  - cmd: mkdir c:\projects\pvpgn\build
  - cmd: cd c:\projects\pvpgn\build

build_script:
  - cmd: cmake -g "Visual Studio 15 2017" -D CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -D WITH_LUA=true -D WITH_MYSQL=%WITH_MYSQL_VAL% -D WITH_ODBC=%WITH_ODBC_VAL% -D WITH_PGSQL=%WITH_PGSQL_VAL% -D WITH_SQLITE3=%WITH_SQLITE3_VAL% -D WITH_WIN32_GUI=true ..
  - cmd: msbuild ALL_BUILD.vcxproj /property:Configuration=RelWithDebInfo /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: rename %programfiles(x86)%\pvpgn\bnetd.exe %programfiles(x86)%\pvpgn\bnetd-gui.exe
  - cmd: rename %programfiles(x86)%\pvpgn\bnetd.pdb %programfiles(x86)%\pvpgn\bnetd-gui.pdb
  - cmd: rename %programfiles(x86)%\pvpgn\d2cs.exe  %programfiles(x86)%\pvpgn\d2cs-gui.exe
  - cmd: rename %programfiles(x86)%\pvpgn\d2cs.pdb  %programfiles(x86)%\pvpgn\d2cs-gui.pdb
  - cmd: rename %programfiles(x86)%\pvpgn\d2dbs.exe %programfiles(x86)%\pvpgn\d2dbs-gui.exe
  - cmd: rename %programfiles(x86)%\pvpgn\d2dbs.pdb %programfiles(x86)%\pvpgn\d2dbs-gui.pdb
  - cmd: cmake -g "Visual Studio 15 2017" -D CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -D WITH_LUA=true -D WITH_MYSQL=%WITH_MYSQL_VAL% -D WITH_ODBC=%WITH_ODBC_VAL% -D WITH_PGSQL=%WITH_PGSQL_VAL% -D WITH_SQLITE3=%WITH_SQLITE3_VAL% -D WITH_WIN32_GUI=false ..
  - cmd: msbuild ALL_BUILD.vcxproj /property:Configuration=RelWithDebInfo /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    - '%programfiles(x86)%\pvpgn\bnetd.exe'
    - '%programfiles(x86)%\pvpgn\bnetd-gui.exe'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: $(programfiles(x86))\pvpgn
    name: pvpgn-pro-$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_COMMIT:~0,7)-$(DB)
    type: zip